-- VISION FUTURE V37.2 — Crypto monitoring
-- Idempotent migration. No existing portfolio or alert data is deleted.

begin;

-- Personal crypto watchlist and optional price thresholds.
create table if not exists public.crypto_watchlist (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    symbol text not null,
    name text,
    price_below numeric,
    price_above numeric,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint crypto_watchlist_symbol_valid
        check (
            symbol = upper(btrim(symbol))
            and symbol ~ '^[A-Z0-9]{2,15}-(USD|EUR)$'
        ),
    constraint crypto_watchlist_price_below_valid
        check (price_below is null or price_below > 0),
    constraint crypto_watchlist_price_above_valid
        check (price_above is null or price_above > 0),
    constraint crypto_watchlist_threshold_order
        check (
            price_below is null
            or price_above is null
            or price_below < price_above
        ),
    constraint crypto_watchlist_user_symbol_key unique (user_id, symbol)
);

alter table public.crypto_watchlist enable row level security;

drop policy if exists crypto_watchlist_select_vf on public.crypto_watchlist;
create policy crypto_watchlist_select_vf
on public.crypto_watchlist for select
to authenticated
using ((select auth.uid()) = user_id and (select public.vf_is_active_user()));

drop policy if exists crypto_watchlist_insert_vf on public.crypto_watchlist;
create policy crypto_watchlist_insert_vf
on public.crypto_watchlist for insert
to authenticated
with check ((select auth.uid()) = user_id and (select public.vf_can_write()));

drop policy if exists crypto_watchlist_update_vf on public.crypto_watchlist;
create policy crypto_watchlist_update_vf
on public.crypto_watchlist for update
to authenticated
using ((select auth.uid()) = user_id and (select public.vf_can_write()))
with check ((select auth.uid()) = user_id and (select public.vf_can_write()));

drop policy if exists crypto_watchlist_delete_vf on public.crypto_watchlist;
create policy crypto_watchlist_delete_vf
on public.crypto_watchlist for delete
to authenticated
using ((select auth.uid()) = user_id and (select public.vf_can_write()));

revoke all on table public.crypto_watchlist from anon, public;
grant select, insert, update, delete on table public.crypto_watchlist to authenticated;
grant usage, select on sequence public.crypto_watchlist_id_seq to authenticated;

create index if not exists crypto_watchlist_enabled_symbol_idx
    on public.crypto_watchlist (enabled, symbol);

-- Keep shared market alerts, but allow position/threshold alerts to be private.
alter table public.market_alerts
    add column if not exists user_id uuid
        references auth.users(id) on delete cascade,
    add column if not exists asset_class text not null default 'EQUITY';

update public.market_alerts
set asset_class = 'CRYPTO'
where symbol ~ '-(USD|EUR)$' and asset_class <> 'CRYPTO';

drop policy if exists market_alerts_authenticated_read_vf on public.market_alerts;
create policy market_alerts_authenticated_read_vf
on public.market_alerts for select
to authenticated
using (
    (select public.vf_is_active_user())
    and (user_id is null or user_id = (select auth.uid()))
);

create index if not exists market_alerts_user_asset_created_idx
    on public.market_alerts (user_id, asset_class, created_at desc);

-- State keys make global signals and each user's position state independent.
alter table public.market_agent_state
    add column if not exists user_id uuid
        references auth.users(id) on delete cascade,
    add column if not exists asset_class text not null default 'EQUITY',
    add column if not exists state_key text;

update public.market_agent_state
set asset_class = 'CRYPTO'
where symbol ~ '-(USD|EUR)$' and asset_class <> 'CRYPTO';

update public.market_agent_state
set state_key = case
    when user_id is null then 'GLOBAL:' || scope || ':' || symbol
    else 'USER:' || user_id::text || ':' || scope || ':' || symbol
end
where state_key is null or btrim(state_key) = '';

alter table public.market_agent_state
    alter column state_key set not null;

drop index if exists public.uq_market_agent_state_symbol_scope;
create unique index if not exists uq_market_agent_state_key
    on public.market_agent_state (state_key);

create index if not exists market_agent_state_user_asset_idx
    on public.market_agent_state (user_id, asset_class, updated_at desc);

-- The former index omitted user_id and could collide across profiles.
drop index if exists public.uq_positions_account_broker_instrument;
create unique index if not exists uq_positions_user_account_broker_instrument
    on public.portfolio_positions (user_id, account, broker, instrument_key);

-- Liquid crypto universe monitored by the existing 15-minute worker.
insert into public.broker_universe
    (symbol, name, isin, market, asset_type, broker, enabled, updated_at)
select seed.symbol, seed.name, null, 'Crypto', 'CRYPTO', 'Crypto', true, now()
from (values
    ('BTC-USD', 'Bitcoin'),
    ('ETH-USD', 'Ethereum'),
    ('SOL-USD', 'Solana'),
    ('BNB-USD', 'BNB'),
    ('XRP-USD', 'XRP'),
    ('ADA-USD', 'Cardano')
) as seed(symbol, name)
where not exists (
    select 1
    from public.broker_universe existing
    where existing.symbol = seed.symbol
      and existing.broker = 'Crypto'
);

commit;
